jwt.secret=tengoqueponerunsecretomuylargoporloqueestoyhaciendounsecretomuylargo
jwt.duration=1
jwt.refresh.duration=10880

# In minutes
activation.duration=5

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dorado.gumoi24@triana.salesianos.edu
spring.mail.password=apyq ssvc nfod ejto
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
