package com.salesianos.triana.DoradoMoises_Ready2Ref.model;

public enum Categoria {

    AUXILIAR, OFICIAL, PROVINCIAL, DIVISION_HONOR, ASISTENTE_3RFEF, RFEF3, ASISTENTE_2RFEF, RFEF2, ASISTENTE_1RFEF, RFEF1, ASISTENTE_SEGUNDA, SEGUNDA, ASISTENTE_PRIMERA, PRIMERA

}
